// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "c82dbbac-03ce-467f-82f5-93144e44f717");
user_pref("app.update.disabledForTesting", true);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1622625843);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1622625939);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "custom");
user_pref("browser.contentblocking.features.standard", "-tp,tpPrivate,cookieBehavior0,-cm,-fp");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1622625840);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 109);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"94922\":1622625939265,\"95042\":1622625939264}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{2e7fb5dc-faad-48d2-a2a4-0df37b06cb26}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1622625842);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1622625843553");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1622647443553");
user_pref("browser.search.region", "CH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210601213358");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1622625939");
user_pref("browser.startup.homepage_override.buildID", "20210601213358");
user_pref("browser.startup.homepage_override.mstone", "91.0a1");
user_pref("browser.startup.lastColdStartupCheck", 1622625939);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"profiler-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.warnOnQuit", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1622625842277");
user_pref("distribution.iniFile.exists.appversion", "91.0a1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "CH");
user_pref("dom.disable_open_during_load", false);
user_pref("dom.push.userAgentID", "a47bab7ebd574d3c8d9ec73bdf812f69");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210601213358");
user_pref("extensions.lastAppVersion", "91.0a1");
user_pref("extensions.lastPlatformVersion", "91.0a1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"f7790d3a-c32c-4887-9807-dd79b10903d5\",\"formautofill@mozilla.org\":\"86043a76-d540-48d9-90fd-a2dc8d1d4f8b\",\"pictureinpicture@mozilla.org\":\"22e96ed3-d9cd-4dee-897e-ba62faf1cc0d\",\"screenshots@mozilla.org\":\"352d90bc-5353-4477-9e59-323f618abb2f\",\"webcompat-reporter@mozilla.org\":\"1ddfc34c-b023-437d-97eb-4e2b95893a54\",\"webcompat@mozilla.org\":\"6844c51a-5d39-499e-93f3-0d1566dc392b\",\"default-theme@mozilla.org\":\"9803ee6e-e6d3-4598-a284-9dd4158f5935\",\"google@search.mozilla.org\":\"ac2e0db2-1808-439e-b118-db4bc6d37e4d\",\"amazondotcom@search.mozilla.org\":\"ec6c44de-9e9f-4362-87f8-945f7e5e673b\",\"wikipedia@search.mozilla.org\":\"2a3710d1-0c1d-4529-ae6f-34a842f857ef\",\"bing@search.mozilla.org\":\"254820be-afd9-4a79-a720-a40f1d6e0ff7\",\"ddg@search.mozilla.org\":\"facd79a5-e18f-43a2-a18b-d5012cb8751a\",\"ebay@search.mozilla.org\":\"29f31021-b0e0-4adc-b380-60c3baa7e724\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1622625842);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("focusmanager.testmode", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.cookieBehavior", 0);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgradeDialog-defaultEnabled\",\"enabled\":true,\"targeting\":\"true\",\"variables\":{},\"description\":\"Turn on upgradeDialog by default for all users\"}");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "6a86613b-bca2-419d-912c-3768b8172df3");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1622625938);
user_pref("toolkit.startup.max_resumed_crashes", -1);
user_pref("toolkit.telemetry.cachedClientID", "29239877-b217-4be5-b432-2894780fde7d");
user_pref("toolkit.telemetry.previousBuildID", "20210601213358");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
